import React from "react";
import HeroSection from "@/pages/landingPage/heroSection/HeroSection";
import FeaturesBenefits from "@/pages/landingPage/featuresBenefits/FeaturesBenefits";
import SocialProof from "@/pages/landingPage/socialProof/SocialProof";
import CTA from "@/pages/landingPage/cta/CTA";
import FormCapture from "@/pages/landingPage/formCapture/FormCapture";
import Footer from "@/components/Footer";
import BotonWpp from "@/components/botonWpp/BotonWpp";
import "./globals.css";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "index",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div>
          <HeroSection />
          <FeaturesBenefits />
          <SocialProof />
          <CTA />
          <FormCapture />
          <Footer />
          <BotonWpp />
      </div>
    </>
  );
}
