import React from "react";
import HeroSection from "@/pages/landingPage/heroSection/HeroSection";
import FeaturesBenefits from "@/pages/landingPage/featuresBenefits/FeaturesBenefits";
import SocialProof from "@/pages/landingPage/socialProof/SocialProof";
import CTA from "@/pages/landingPage/cta/CTA";
import FormCapture from "@/pages/landingPage/formCapture/FormCapture";
import Footer from "@/components/Footer";
import BotonWpp from "@/components/botonWpp/BotonWpp";
import "./globals.css";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "index",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    <header className="bg-blue-600 text-white py-4">
      <div className="container mx-auto flex justify-between items-center px-4">
        <h1 className="text-3xl font-bold">Cotización App</h1>
      </div>
    </header>
      <div className="max-w-screen overflow-hidden mx-auto">
        <HeroSection />
        <FeaturesBenefits />
        <SocialProof />
        <CTA />
        <FormCapture />
        <Footer />
        <BotonWpp />
      </div>
    </>
  );
}
